#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allrun.pre

application=`getApplication`

runApplication decomposePar

runParallel $application 4

#~ runApplication reconstructParMesh -mergeTol 1e-6 -constant
runApplication reconstructPar

